name: Update Coins Data

permissions:
  contents: write

on:
  schedule:
    # Runs every day at 02:00 UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # allows manual trigger from GitHub Actions tab

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Ensure public/coins folder exists
        run: mkdir -p public/coins

      - name: Run coin update script
        run: npm run update-coins

      - name: Commit and push updated coins data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public/coins.json public/coins/
          git commit -m "Update coins data [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
